"""Export analysis results to markdown and JSON files."""

from __future__ import annotations

import json
from dataclasses import asdict
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional

from .models import ProjectAnalysis, ScanOptions


def export_all(
    analysis: ProjectAnalysis,
    prompts: Dict[str, str],
    options: ScanOptions,
) -> List[Path]:
    """
    Export all output files for a scan.

    Returns a list of created file paths.
    """
    output_dir = options.output_path
    output_dir.mkdir(parents=True, exist_ok=True)

    prompts_dir = output_dir / "prompts"
    prompts_dir.mkdir(parents=True, exist_ok=True)

    created: List[Path] = []

    # Core markdown files
    created.append(_write(output_dir / "project_summary.md", _build_project_summary_md(analysis)))
    created.append(_write(output_dir / "file_tree.md", _build_file_tree_md(analysis)))
    created.append(_write(output_dir / "tech_stack.md", _build_tech_stack_md(analysis)))
    created.append(_write(output_dir / "risk_notes.md", _build_risk_notes_md(analysis)))
    created.append(_write(output_dir / "redaction_report.md", _build_redaction_report_md(analysis)))

    # Scan report JSON
    created.append(_write(output_dir / "scan_report.json", _build_scan_report_json(analysis, options)))

    # Prompt files
    for model_name, prompt_content in prompts.items():
        prompt_path = prompts_dir / f"{model_name}_prompt.md"
        created.append(_write(prompt_path, prompt_content))

    return created


def _write(path: Path, content: str) -> Path:
    """Write content to a file and return the path."""
    path.write_text(content, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Markdown builders
# ---------------------------------------------------------------------------


def _build_project_summary_md(analysis: ProjectAnalysis) -> str:
    meta = analysis.scan_metadata
    stack = analysis.tech_stack

    lines = [
        "# Project Summary",
        "",
        f"**Project Path:** `{analysis.project_path}`",
        f"**Scanned At:** {meta.scanned_at if meta else 'N/A'}",
        f"**Scan ID:** `{meta.scan_id if meta else 'N/A'}`",
        "",
        "---",
        "",
        "## Overview",
        "",
        analysis.project_summary or "_No project summary available. Ollama summarization may have been disabled or unavailable._",
        "",
        "---",
        "",
        "## Technology Stack",
        "",
    ]

    if stack.languages:
        lines.append(f"- **Languages:** {', '.join(stack.languages)}")
    if stack.frameworks:
        lines.append(f"- **Frameworks:** {', '.join(stack.frameworks)}")
    if stack.libraries:
        lines.append(f"- **Libraries:** {', '.join(stack.libraries)}")
    if stack.databases:
        lines.append(f"- **Databases / ORM:** {', '.join(stack.databases)}")
    if stack.tools:
        lines.append(f"- **Tools:** {', '.join(stack.tools)}")
    if stack.package_managers:
        lines.append(f"- **Package Managers:** {', '.join(stack.package_managers)}")
    if stack.testing_tools:
        lines.append(f"- **Testing:** {', '.join(stack.testing_tools)}")

    if stack.is_empty():
        lines.append("_No technologies detected._")

    lines += [
        "",
        "---",
        "",
        "## Scan Statistics",
        "",
        f"| Metric | Value |",
        f"|---|---|",
        f"| Files Scanned | {meta.files_scanned if meta else 'N/A'} |",
        f"| Files Skipped | {meta.files_skipped if meta else 'N/A'} |",
        f"| Files Redacted | {meta.files_redacted if meta else 'N/A'} |",
        f"| Ollama Used | {meta.ollama_used if meta else 'N/A'} |",
        f"| Ollama Model | {meta.ollama_model if meta else 'N/A'} |",
        f"| Duration | {f'{meta.duration_seconds:.1f}s' if meta else 'N/A'} |",
        "",
    ]

    if meta and meta.ollama_error:
        lines += [
            "---",
            "",
            f"> ⚠ **Ollama Note:** {meta.ollama_error}",
            "",
        ]

    lines += [
        "---",
        "",
        "_Generated by Local Project Prompt Generator v1.0.0_",
        "_This tool does not send code to cloud AI automatically._",
        "_Prompts are prepared locally. You decide what to copy into ChatGPT, Claude, Gemini, MiniMax, or another model._",
    ]

    return "\n".join(lines)


def _build_file_tree_md(analysis: ProjectAnalysis) -> str:
    return "\n".join([
        "# File Tree",
        "",
        "```",
        analysis.file_tree,
        "```",
        "",
        "_Generated by Local Project Prompt Generator v1.0.0_",
    ])


def _build_tech_stack_md(analysis: ProjectAnalysis) -> str:
    stack = analysis.tech_stack
    lines = [
        "# Detected Technology Stack",
        "",
        "| Category | Detected Technologies |",
        "|---|---|",
    ]

    categories = [
        ("Languages", stack.languages),
        ("Frameworks", stack.frameworks),
        ("Libraries", stack.libraries),
        ("Databases / ORM", stack.databases),
        ("Tools", stack.tools),
        ("Package Managers", stack.package_managers),
        ("Testing Tools", stack.testing_tools),
    ]

    for category, items in categories:
        value = ", ".join(items) if items else "_None detected_"
        lines.append(f"| {category} | {value} |")

    lines += [
        "",
        "---",
        "",
        "## Detection Method",
        "",
        "Technologies are detected by inspecting config files and dependency manifests:",
        "- `package.json`, `tsconfig.json`, `vite.config.*`, `next.config.*`",
        "- `requirements.txt`, `pyproject.toml`, `Pipfile`, `manage.py`",
        "- `composer.json`, `artisan`",
        "- `pom.xml`, `build.gradle`, `build.gradle.kts`",
        "- `*.csproj`, `appsettings.json`",
        "- `prisma/schema.prisma`",
        "- `docker-compose.yml`, `Dockerfile`",
        "",
        "_Generated by Local Project Prompt Generator v1.0.0_",
    ]

    return "\n".join(lines)


def _build_risk_notes_md(analysis: ProjectAnalysis) -> str:
    lines = [
        "# Risk Notes",
        "",
        "_These risk notes were generated based on static analysis and file scanning._",
        "",
    ]

    if analysis.risk_notes:
        for note in analysis.risk_notes:
            lines.append(f"- {note}")
    else:
        lines.append("_No specific risk notes were generated._")

    lines += [
        "",
        "---",
        "",
        "## Redaction Summary",
        "",
    ]

    if analysis.redaction_findings:
        lines += [
            f"**{len(analysis.redaction_findings)} secret pattern(s) were detected and redacted.**",
            "",
            "| File | Finding Type | Count |",
            "|---|---|---|",
        ]
        for finding in analysis.redaction_findings:
            lines.append(f"| `{finding.file_path}` | {finding.finding_type} | {finding.count} |")
        lines += [
            "",
            "> ⚠ Secret values were replaced with placeholders and are NOT included in any output.",
        ]
    else:
        lines.append("_No secrets were detected or redacted._")

    lines += [
        "",
        "---",
        "",
        "_Generated by Local Project Prompt Generator v1.0.0_",
    ]

    return "\n".join(lines)


def _build_redaction_report_md(analysis: ProjectAnalysis) -> str:
    lines = [
        "# Redaction Report",
        "",
        "_This report documents all secrets and sensitive values that were detected and redacted._",
        "_Secret values are NEVER included in any output file or prompt._",
        "",
        "---",
        "",
    ]

    if not analysis.redaction_findings:
        lines += [
            "## Result",
            "",
            "✓ **No secrets were detected in scanned files.**",
            "",
            "_Note: Secret files (.env, .pem, .key, etc.) are always excluded from scanning entirely._",
        ]
    else:
        total_count = sum(f.count for f in analysis.redaction_findings)
        affected_files = len(set(f.file_path for f in analysis.redaction_findings))

        lines += [
            "## Summary",
            "",
            f"- **Total redactions:** {total_count}",
            f"- **Affected files:** {affected_files}",
            f"- **Finding types:** {', '.join(set(f.finding_type for f in analysis.redaction_findings))}",
            "",
            "---",
            "",
            "## Findings",
            "",
            "| File | Finding Type | Count | Placeholder Used |",
            "|---|---|---|---|",
        ]

        placeholder_map = {
            "API_KEY": "[REDACTED_SECRET]",
            "TOKEN": "[REDACTED_TOKEN]",
            "PASSWORD": "[REDACTED_PASSWORD]",
            "PRIVATE_KEY": "[REDACTED_PRIVATE_KEY]",
            "SECRET": "[REDACTED_SECRET]",
            "CONNECTION_STRING": "[REDACTED_SECRET]",
            "AWS_KEY": "[REDACTED_SECRET]",
            "GENERIC_SECRET": "[REDACTED_SECRET]",
        }

        for finding in analysis.redaction_findings:
            placeholder = placeholder_map.get(finding.finding_type, "[REDACTED_SECRET]")
            lines.append(f"| `{finding.file_path}` | {finding.finding_type} | {finding.count} | `{placeholder}` |")

        lines += [
            "",
            "---",
            "",
            "## Security Notes",
            "",
            "- All detected secret values were replaced with placeholders before any summarization.",
            "- Secret files (.env, .env.*, .pem, .key, .crt, id_rsa, etc.) were excluded from scanning entirely.",
            "- This tool never uploads any file content to external services.",
            "- Review your source files to ensure secrets are properly managed (use environment variables, secret managers).",
        ]

    lines += [
        "",
        "---",
        "",
        "_Generated by Local Project Prompt Generator v1.0.0_",
    ]

    return "\n".join(lines)


def _build_scan_report_json(analysis: ProjectAnalysis, options: ScanOptions) -> str:
    """Build the scan_report.json content."""
    meta = analysis.scan_metadata

    report = {
        "scan_id": meta.scan_id if meta else "unknown",
        "scanned_at": meta.scanned_at if meta else "unknown",
        "project_path": analysis.project_path,
        "options": {
            "output_path": str(options.output_path),
            "model": options.model,
            "ollama_url": options.ollama_url,
            "max_files": options.max_files,
            "max_chars_per_file": options.max_chars_per_file,
            "use_ollama": options.use_ollama,
            "target_model": options.target_model,
            "mode": options.mode,
            "use_cache": options.use_cache,
        },
        "analysis": {
            "mode": meta.mode if meta else "fast",
            "evidence_level": meta.evidence_level if meta else "limited",
            "detected_domain": meta.domain_result.domain if meta and meta.domain_result else "generic",
            "domain_confidence": meta.domain_result.confidence if meta and meta.domain_result else "low",
            "domain_score": meta.domain_result.score if meta and meta.domain_result else 0,
        },
        "statistics": {
            "total_files_found": meta.total_files_found if meta else 0,
            "files_scanned": meta.files_scanned if meta else 0,
            "files_skipped": meta.files_skipped if meta else 0,
            "files_redacted": meta.files_redacted if meta else 0,
            "duration_seconds": meta.duration_seconds if meta else 0,
        },
        "ollama": {
            "used": meta.ollama_used if meta else False,
            "available": meta.ollama_available if meta else False,
            "model": meta.ollama_model if meta else options.model,
            "error": meta.ollama_error if meta else None,
            "summarization_status": (
                "completed" if (meta and meta.ollama_used)
                else "skipped_disabled" if (meta and not options.use_ollama)
                else "skipped_unavailable"
            ),
        },
        "tech_stack": {
            "languages": analysis.tech_stack.languages,
            "frameworks": analysis.tech_stack.frameworks,
            "libraries": analysis.tech_stack.libraries,
            "databases": analysis.tech_stack.databases,
            "tools": analysis.tech_stack.tools,
            "package_managers": analysis.tech_stack.package_managers,
            "testing_tools": analysis.tech_stack.testing_tools,
        },
        "redaction": {
            "total_findings": len(analysis.redaction_findings),
            "total_redactions": sum(f.count for f in analysis.redaction_findings),
            "affected_files": list(set(f.file_path for f in analysis.redaction_findings)),
            "findings": [
                {
                    "file_path": f.file_path,
                    "finding_type": f.finding_type,
                    "count": f.count,
                }
                for f in analysis.redaction_findings
            ],
        },
        "important_files": [
            {
                "path": f.relative_path,
                "priority_score": f.priority_score,
                "size": f.size,
                "redacted": f.redacted,
            }
            for f in analysis.important_files[:50]
        ],
        "assumptions": analysis.assumptions,
        "risk_notes": analysis.risk_notes,
        "generator": "Local Project Prompt Generator v1.0.0",
        "security_note": (
            "This tool does not send code to cloud AI automatically. "
            "Prompts are prepared locally. The user manually decides what to copy into ChatGPT, Claude, Gemini, MiniMax, or another model."
        ),
    }

    return json.dumps(report, indent=2, ensure_ascii=False)
