"""ChatGPT-optimized prompt template."""

from __future__ import annotations

from ..models import ProjectAnalysis
from ._common import build_common_prompt_sections, build_tech_stack_table


def build_chatgpt_prompt(analysis: ProjectAnalysis) -> str:
    """
    Build a ChatGPT-optimized prompt from a ProjectAnalysis.

    Style: clear role definition, phased analysis, tables, explicit constraints.
    """
    stack = analysis.tech_stack
    meta = analysis.scan_metadata

    tech_table = build_tech_stack_table(stack)

    # Important files list
    important_files_section = _build_important_files_section(analysis)

    # File summaries
    file_summaries_section = _build_file_summaries_section(analysis)

    # Risk notes
    risk_section = _build_risk_section(analysis)

    # Redaction note
    redaction_note = _build_redaction_note(analysis)

    # Scan metadata
    scan_info = _build_scan_info(meta)

    prompt = f"""# Role

You are a senior Tech Lead, software architect, security reviewer, and code quality expert.

---

# Mission

Analyze this project based on the local pre-analysis summary provided below.
This summary was generated by a local tool - no source files were uploaded to any cloud service.
Treat the pre-analysis as evidence, not as absolute truth.

---

# Rules

- **Do NOT ask questions until all phases are completed.**
- If information is missing, make reasonable assumptions and label them clearly.
- Clearly separate **facts** from **assumptions**.
- Prioritize critical security and architecture risks.
- Give actionable refactor recommendations.
- Produce a final technical report.
- Do not claim to have read files that were not included in the summary.
- Mention uncertainty where needed.

---

# Project Facts

| Field | Value |
|---|---|
| Project Path | `{analysis.project_path}` |
| Files Scanned | {meta.files_scanned if meta else 'N/A'} |
| Files Skipped | {meta.files_skipped if meta else 'N/A'} |
| Files Redacted | {meta.files_redacted if meta else 'N/A'} |
| Ollama Used | {meta.ollama_used if meta else 'N/A'} |
| Scan Date | {meta.scanned_at if meta else 'N/A'} |

---

# Detected Stack

{tech_table}

---

# Important Files

{important_files_section}

---

# File Summaries

{file_summaries_section}

---

# Risk Notes

{risk_section}

---

# Redaction Report

{redaction_note}

---

# File Tree

```
{analysis.file_tree}
```

---

# Project Summary

{analysis.project_summary or '_No project summary available._'}

---

# Analysis Phases

Complete **all** of the following phases before producing output:

1. **Understand Project Purpose** — What does this project do? Who uses it?
2. **Review Architecture** — What is the overall architecture? Monolith, microservices, layered?
3. **Review Technology Stack** — Is the stack appropriate? Any outdated or risky dependencies?
4. **Review Folder Structure** — Is the structure clean and maintainable?
5. **Review Database and Data Model** — What databases/ORMs are used? Any schema concerns?
6. **Review Authentication and Authorization** — How is auth handled? Any gaps?
7. **Review Security Risks** — Any hardcoded secrets, injection risks, missing validation?
8. **Review Code Quality** — Patterns, anti-patterns, complexity, duplication?
9. **Review Test Coverage** — What testing tools exist? Are critical paths covered?
10. **Review Deployment/Build Risks** — Docker, CI/CD, environment config risks?
11. **Produce Prioritized Action Plan** — What should be fixed first?

---

# Expected Output

Produce a structured technical report with these sections:

1. **Executive Summary** (3-5 sentences)
2. **Detected Stack** (confirm or correct the detected stack)
3. **Architecture Review** (patterns, strengths, weaknesses)
4. **Security Findings** (table: Finding | Severity | File | Recommendation)
5. **Database Review** (schema, ORM usage, migration strategy)
6. **Code Quality Review** (patterns, anti-patterns, maintainability)
7. **Testing Gaps** (what's missing, what's covered)
8. **Risk Table** (Risk | Likelihood | Impact | Priority)
9. **Refactor Plan** (prioritized list of improvements)
10. **Final Verdict** (overall health score 1-10 with justification)

---

# Final Instructions

- Complete all 11 analysis phases before writing the report.
- Do NOT ask clarifying questions — make reasonable assumptions.
- Use tables where they improve clarity.
- Be specific and actionable.
- Flag any critical security issues prominently.

---

{build_common_prompt_sections(analysis)}

{scan_info}
"""
    return prompt.strip()


def _build_important_files_section(analysis: ProjectAnalysis) -> str:
    if not analysis.important_files:
        return "_No important files identified._"
    lines = []
    for f in analysis.important_files[:30]:
        lines.append(f"- `{f.relative_path}` (priority: {f.priority_score}, size: {f.size}B{', redacted' if f.redacted else ''})")
    return "\n".join(lines)


def _build_file_summaries_section(analysis: ProjectAnalysis) -> str:
    if not analysis.file_summaries:
        return "_No file summaries available (static analysis mode)._"
    lines = []
    for path, summary in list(analysis.file_summaries.items())[:40]:
        lines.append(f"### `{path}`\n{summary}\n")
    return "\n".join(lines)


def _build_risk_section(analysis: ProjectAnalysis) -> str:
    if not analysis.risk_notes:
        return "_No specific risk notes generated._"
    return "\n".join(f"- {note}" for note in analysis.risk_notes)


def _build_redaction_note(analysis: ProjectAnalysis) -> str:
    if not analysis.redaction_findings:
        return "_No secrets were detected or redacted._"
    lines = ["The following secret patterns were detected and redacted before this prompt was generated:\n"]
    lines.append("| File | Finding Type | Count |")
    lines.append("|---|---|---|")
    for finding in analysis.redaction_findings:
        lines.append(f"| `{finding.file_path}` | {finding.finding_type} | {finding.count} |")
    lines.append("\n> ⚠ Secret values were replaced with placeholders. They are NOT included in this prompt.")
    return "\n".join(lines)


def _build_scan_info(meta) -> str:
    if not meta:
        return ""
    ollama_note = ""
    if meta.ollama_error:
        ollama_note = f"\n> ⚠ Ollama Note: {meta.ollama_error}"
    return f"\n---\n\n_Scan ID: {meta.scan_id} | Generated by Local Project Prompt Generator v1.0.0_{ollama_note}"
