"""Generic universal prompt template."""

from __future__ import annotations

from ..models import ProjectAnalysis
from ._common import build_common_prompt_sections, build_tech_stack_table


def build_generic_prompt(analysis: ProjectAnalysis) -> str:
    """
    Build a generic universal prompt from a ProjectAnalysis.

    Style: universal, role + context + tasks + rules + output format.
    """
    stack = analysis.tech_stack
    meta = analysis.scan_metadata

    prompt = f"""# Role

You are a senior Tech Lead, software architect, security reviewer, and code quality expert.

---

# Context

You have been provided with a locally generated pre-analysis summary of a software project.
This summary was produced by a local tool — no source files were uploaded to any cloud service.
Use this summary as evidence to perform a thorough technical analysis.

**Project Path:** `{analysis.project_path}`
**Scanned At:** {meta.scanned_at if meta else 'N/A'}
**Scan ID:** {meta.scan_id if meta else 'N/A'}

---

# Project Summary

{analysis.project_summary or 'No Ollama summary available. Use the data sections below.'}

---

### Tech Stack

{build_tech_stack_table(stack)}

---

# File Tree

```
{analysis.file_tree}
```

---

# Important Files

{_build_important_files(analysis)}

---

# File Summaries

{_build_file_summaries(analysis)}

---

# Risk Notes

{_build_risks(analysis)}

---

# Redaction Report

{_build_redaction(analysis)}

---

# Scan Metadata

- Files Scanned: {meta.files_scanned if meta else 'N/A'}
- Files Skipped: {meta.files_skipped if meta else 'N/A'}
- Files Redacted: {meta.files_redacted if meta else 'N/A'}
- Ollama Used: {meta.ollama_used if meta else 'N/A'}
{f'- Ollama Note: {meta.ollama_error}' if meta and meta.ollama_error else ''}

---

# Tasks

Analyze this project by completing all of the following tasks:

1. Understand the project's purpose and intended users.
2. Review the overall architecture — patterns, layers, separation of concerns.
3. Review the technology stack — appropriateness, risks, outdated dependencies.
4. Review the folder structure — organization, maintainability, naming conventions.
5. Review the database and data model — schema design, ORM usage, migration strategy.
6. Review authentication and authorization — mechanisms, gaps, security posture.
7. Review security risks — secrets exposure, injection risks, input validation, CORS, rate limiting.
8. Review code quality — patterns, anti-patterns, complexity, duplication, readability.
9. Review test coverage — what is tested, what is missing, test quality.
10. Review deployment and build risks — Docker, CI/CD, environment configuration.
11. Produce a prioritized action plan.

---

# Rules

- Do NOT ask questions until all tasks are completed.
- If information is missing, make reasonable assumptions and label them clearly.
- Clearly separate facts from assumptions.
- Prioritize critical security and architecture risks.
- Give actionable refactor recommendations.
- Do not claim to have read files that were not included in the summary.
- Treat the pre-analysis as evidence, not as absolute truth.
- Mention uncertainty where needed.

---

# Output Format

Produce a structured technical report with these sections:

1. **Executive Summary** (3-5 sentences)
2. **Detected Stack** (confirm or correct)
3. **Architecture Review** (pattern, strengths, weaknesses)
4. **Security Findings** (table: Finding | Severity | File/Area | Recommendation)
5. **Database Review** (schema, ORM, migrations, risks)
6. **Code Quality Review** (patterns, anti-patterns, maintainability)
7. **Testing Gaps** (coverage assessment, missing tests)
8. **Risk Table** (Risk | Likelihood | Impact | Priority)
9. **Refactor Plan** (prioritized improvements)
10. **Final Verdict** (health score 1-10 + top 3 immediate actions)

---

{build_common_prompt_sections(analysis)}

---

# Final Report Expectations

- Be specific and actionable.
- Use tables and lists where they improve clarity.
- Flag critical security issues prominently.
- Complete all 11 tasks before writing the report.
- Provide a clear, honest assessment of the project's health.

_Generated by Local Project Prompt Generator v1.0.0_
"""
    return prompt.strip()


def _build_important_files(analysis: ProjectAnalysis) -> str:
    if not analysis.important_files:
        return "_No important files identified._"
    lines = []
    for f in analysis.important_files[:30]:
        note = " *(redacted)*" if f.redacted else ""
        lines.append(f"- `{f.relative_path}` (priority: {f.priority_score}){note}")
    return "\n".join(lines)


def _build_file_summaries(analysis: ProjectAnalysis) -> str:
    if not analysis.file_summaries:
        return "_No file summaries available (static analysis mode)._"
    lines = []
    for path, summary in list(analysis.file_summaries.items())[:40]:
        lines.append(f"### `{path}`\n{summary}\n")
    return "\n".join(lines)


def _build_risks(analysis: ProjectAnalysis) -> str:
    if not analysis.risk_notes:
        return "_No specific risk notes generated._"
    return "\n".join(f"- {note}" for note in analysis.risk_notes)


def _build_redaction(analysis: ProjectAnalysis) -> str:
    if not analysis.redaction_findings:
        return "_No secrets were detected or redacted._"
    lines = ["The following secret patterns were detected and redacted:"]
    for finding in analysis.redaction_findings:
        lines.append(f"- `{finding.file_path}`: {finding.finding_type} ({finding.count} occurrence(s))")
    lines.append("\n> Secret values are NOT included in this prompt.")
    return "\n".join(lines)
