"""MiniMax-optimized prompt template — compact, agent-based, direct."""

from __future__ import annotations

from ..models import ProjectAnalysis
from ._common import build_common_prompt_sections, build_tech_stack_table


def build_minimax_prompt(analysis: ProjectAnalysis) -> str:
    """
    Build a MiniMax-optimized prompt from a ProjectAnalysis.

    Style: compact, agent/task-based, direct, implementation-oriented.
    """
    stack = analysis.tech_stack
    meta = analysis.scan_metadata

    prompt = f"""## Agent Role

You are a senior Tech Lead, software architect, security reviewer, and code quality expert.
Analyze the project pre-analysis below and produce a prioritized technical report.
No source files were uploaded — this is a locally generated summary.

---

## Objective

Perform a complete technical analysis of the project described below.
Identify risks, architecture issues, security gaps, and quality problems.
Produce a prioritized action plan.

---

## Input Summary

**Project:** `{analysis.project_path}`
**Scanned:** {meta.scanned_at if meta else 'N/A'} | Files: {meta.files_scanned if meta else 'N/A'} scanned, {meta.files_skipped if meta else 'N/A'} skipped
**Ollama Used:** {meta.ollama_used if meta else 'N/A'}{f' | Note: {meta.ollama_error}' if meta and meta.ollama_error else ''}

**Stack:**
{build_tech_stack_table(stack)}

**Project Summary:**
{analysis.project_summary or 'Not available. Use file summaries and file tree below.'}

**File Tree:**
```
{analysis.file_tree[:3000]}{'...[truncated]' if len(analysis.file_tree) > 3000 else ''}
```

**Important Files:**
{_build_important_files(analysis)}

**File Summaries:**
{_build_file_summaries(analysis)}

**Risk Notes:**
{_build_risks(analysis)}

**Redaction Report:**
{_build_redaction(analysis)}

---

## Tasks

Execute all tasks. Do not ask questions. Make assumptions where needed and label them.

1. Identify project purpose and type.
2. Analyze architecture — pattern, layers, module boundaries.
3. Validate tech stack — appropriateness, risks, outdated deps.
4. Analyze folder structure — organization, naming, anti-patterns.
5. Analyze database/data model — schema, ORM, migrations, integrity.
6. Analyze auth/authz — mechanisms, gaps, security posture.
7. Identify security risks — secrets, injection, validation, CORS, rate limiting.
8. Assess code quality — patterns, complexity, duplication, readability.
9. Assess test coverage — what exists, what's missing, critical gaps.
10. Assess deployment/build risks — Docker, CI/CD, env config.
11. Build prioritized action plan — Critical → High → Medium → Low.

---

## Priority Rules

- **P0 (Critical):** Security vulnerabilities, data exposure, auth bypass risks.
- **P1 (High):** Architecture flaws, missing critical tests, broken patterns.
- **P2 (Medium):** Code quality issues, missing documentation, tech debt.
- **P3 (Low):** Style issues, minor improvements, nice-to-haves.

Always surface P0 and P1 issues first.

---

## Output Format

Produce a concise but complete technical report:

1. **Executive Summary** (2-3 sentences)
2. **Stack** (confirmed/corrected)
3. **Architecture** (pattern + key observations)
4. **Security Findings** (table: Issue | Severity | Location | Fix)
5. **Database** (schema + ORM + risks)
6. **Code Quality** (key observations)
7. **Testing** (coverage + gaps)
8. **Risk Table** (Risk | P-Level | Action)
9. **Action Plan** (P0 → P1 → P2 → P3)
10. **Verdict** (score 1-10 + top 3 actions)

{build_common_prompt_sections(analysis)}

_Generated by Local Project Prompt Generator v1.0.0_
"""
    return prompt.strip()


def _build_important_files(analysis: ProjectAnalysis) -> str:
    if not analysis.important_files:
        return "None identified."
    lines = []
    for f in analysis.important_files[:20]:
        note = " [REDACTED]" if f.redacted else ""
        lines.append(f"- `{f.relative_path}`{note}")
    return "\n".join(lines)


def _build_file_summaries(analysis: ProjectAnalysis) -> str:
    if not analysis.file_summaries:
        return "Not available (static mode)."
    lines = []
    for path, summary in list(analysis.file_summaries.items())[:30]:
        # Keep compact for MiniMax
        short_summary = summary[:300] + "..." if len(summary) > 300 else summary
        lines.append(f"[{path}] {short_summary}")
    return "\n".join(lines)


def _build_risks(analysis: ProjectAnalysis) -> str:
    if not analysis.risk_notes:
        return "None noted."
    return "\n".join(f"- {note}" for note in analysis.risk_notes)


def _build_redaction(analysis: ProjectAnalysis) -> str:
    if not analysis.redaction_findings:
        return "No secrets detected."
    lines = []
    for finding in analysis.redaction_findings:
        lines.append(f"- `{finding.file_path}`: {finding.finding_type} ({finding.count}x) — REDACTED")
    return "\n".join(lines)
